In [1]:
import requests
import pandas as pd 
import numpy as np

In [2]:
data = requests.get('https://d946a72959ed.ngrok.io/data').json()
data.keys()

dict_keys([&#39;test2&#39;, &#39;Krzysiujestsuper&#39;, &#39;test3&#39;, &#39;test4&#39;, &#39;test5&#39;, &#39;test7&#39;, &#39;room_Jan&#39;, &#39;test8&#39;])

In [3]:
real_data_df = pd.DataFrame(data['room_Jan'])

In [4]:
# During the analysis I didn't know which column represents sensors, and which represents devices. 
# That is why I have performed some data analysis to determine it. Also all sensors values have been 
# standarized, so that machine learning algorithms can converge easly to global minimum of 
# cost function. 

In [5]:
print(real_data_df[0].describe())
real_data_df[0].unique()
# strings representing date, primary key of each table in the smarthouse project database

count                        18977
unique                       18977
top       Thu Oct  1 06:56:12 2020
freq                             1
Name: 0, dtype: object


array([&#39;Sun Sep 27 23:24:05 2020&#39;, &#39;Sun Sep 27 23:24:35 2020&#39;,
       &#39;Sun Sep 27 23:24:55 2020&#39;, ..., &#39;Fri Oct  2 09:26:59 2020&#39;,
       &#39;Fri Oct  2 09:27:19 2020&#39;, &#39;Fri Oct  2 09:27:39 2020&#39;],
      dtype=object)

In [6]:
print(real_data_df[1].describe())
real_data_df[1].unique()
# values between 0.0 and 0.65, it is probably light sensor

count    18977.000000
mean         0.184900
std          0.205119
min          0.000000
25%          0.000000
50%          0.110000
75%          0.380000
max          0.650000
Name: 1, dtype: float64


array([0.49, 0.23, 0.24, 0.52, 0.51, 0.48, 0.5 , 0.46, 0.45, 0.43, 0.4 ,
       0.  , 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33, 0.34,
       0.35, 0.36, 0.37, 0.38, 0.39, 0.41, 0.42, 0.44, 0.47, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.22, 0.21, 0.2 , 0.19, 0.18, 0.17, 0.16, 0.15, 0.14, 0.13, 0.12,
       0.11, 0.1 , 0.09, 0.08, 0.07, 0.06, 0.05, 0.04, 0.03, 0.02, 0.01])

In [7]:
print(real_data_df[2].describe())
real_data_df[2].unique()
# real values between 0 and 22.1, also some 'nan' included, probably it is temperature sensor

count     18977.0
unique       64.0
top          22.1
freq       2189.0
Name: 2, dtype: float64


array([21, 20.9, 21.1, 21.2, 21.3, 21.4, 21.5, 21.6, 21.7, &#39;nan&#39;, 20.8,
       20.5, 20.2, 19.8, 19.6, 19.2, 19, 18.7, 18.5, 18.3, 18.1, 18, 17.8,
       17.7, 17.6, 17.5, 17.4, 17.3, 17.2, 17.1, 17, 16.9, 16.8, 16.7,
       16.6, 16.5, 16.4, 16.3, 16.2, 16.1, 17.9, 18.2, 18.4, 18.6, 18.8,
       18.9, 19.1, 19.3, 19.4, 19.5, 19.7, 19.9, 20, 20.1, 20.3, 20.4,
       20.6, 20.7, 21.8, 21.9, 22, 22.1, 22.2, 22.3], dtype=object)

In [8]:
print(real_data_df[3].describe())
real_data_df[3].unique()
# only zeros and ones, it is controllable divice

count    18977.000000
mean         0.087738
std          0.282921
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: 3, dtype: float64


array([0, 1], dtype=int64)

In [9]:
print(real_data_df[4].describe())
real_data_df[4].unique()
# only zeros and ones, it is controllable divice

count    18977.000000
mean         0.519471
std          0.499634
min          0.000000
25%          0.000000
50%          1.000000
75%          1.000000
max          1.000000
Name: 4, dtype: float64


array([0, 1], dtype=int64)

In [10]:
print(real_data_df[5].describe())
real_data_df[5].unique()
# only zeros and ones, it is controllable divice

count    18977.000000
mean         0.106497
std          0.308481
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: 5, dtype: float64


array([1, 0], dtype=int64)

In [11]:
real_data_df.columns = ['date', 'sensor_1', 'sensor_2', 'device_1', 'device_2', 'device_3']
real_data_df.index = real_data_df['date']
real_data_df = real_data_df.drop(columns = ['date'])

In [12]:
real_data_df

sensor_1 sensor_2  device_1  device_2  device_3
date                                                                     
Sun Sep 27 23:24:05 2020      0.49       21         0         0         1
Sun Sep 27 23:24:35 2020      0.23       21         0         0         1
Sun Sep 27 23:24:55 2020      0.23       21         0         0         1
Sun Sep 27 23:25:15 2020      0.24       21         0         0         1
Sun Sep 27 23:25:35 2020      0.23       21         0         0         1
...                            ...      ...       ...       ...       ...
Fri Oct  2 09:26:19 2020      0.31     21.8         0         1         0
Fri Oct  2 09:26:39 2020      0.31     21.8         0         1         0
Fri Oct  2 09:26:59 2020      0.32     21.8         0         1         0
Fri Oct  2 09:27:19 2020      0.33     21.8         0         1         0
Fri Oct  2 09:27:39 2020      0.33     21.8         0         1         0

[18977 rows x 5 columns]

In [13]:
# Next step is to determine best rule indiction algorithm. Our goal is to find a rule 
# of behaviours between devices and sensors, so that our algorithm can predict properly when it should
# activate each device. 2 algorithms I am going to compare are Decision Trees, Random Forest and Extreeme Gradient Boosted Trees.

In [14]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn import metrics

from copy import deepcopy
import itertools

In [15]:
from sklearn.metrics import fbeta_score

def f1_score(y_true, y_pred, threshold = 0.5):
    y_pred_class = y_pred >= threshold
    y_true = y_true == 1
    return fbeta_score(y_true, y_pred_class, beta = 1)

In [29]:
class AutoTuningHyperparametersPipeline(object):
    @staticmethod
    def standarize(X):
        data = deepcopy(X.replace(['nan'], 0))
        for column_name in data.columns:
            if 'sensor' in column_name:
                data[column_name] = (data[column_name] - data[column_name].mean())/data[column_name].std()
        return data

    @staticmethod
    def generate_all_possible_params(params):
        keys, values = zip(*params.items())
        possible_params = [dict(zip(keys, v)) for v in itertools.product(*values)]
        return possible_params

    def __init__(self, model, X, y, params, cost):
        self.model = model 
        X = self.standarize(X) 
        self.X_train = X[:int(0.7*len(X))]
        self.X_test = X[int(0.7*len(X)):]
        self.y_train = y[:int(0.7*len(y))]
        self.y_test = y[int(0.7*len(y)):]
        self.params = self.generate_all_possible_params(params)
        self.cost = cost
        self.best_model = None
    
    def fit_model(self, params):
        model = self.model(**params)
        model.fit(self.X_train, self.y_train)
        predictions = model.predict(self.X_test)
        return model, self.cost(self.y_test, predictions)
    
    def grid_search(self, verbose = 1):
        models = []
        for index, parameters in enumerate(self.params):
            model, ratio = self.fit_model(parameters)
            models.append([parameters, ratio])

            if verbose >= 1:
                print('{:.4f}'.format((index+1)/len(self.params)), start = '\r')

        sorted_models = [[x[0], x[1]] for x in sorted(models, key = lambda x: x[1])]
        self.best_model = sorted_models[-1]
        return self.best_model[0], self.best_model[1]

    def random_search(self, verbose = 1, group_size = 5, iterations = 20, params = None):
        if params:
            params = self.generate_all_possible_params(params)
        else:
            params = self.params

        models = []
        for iteration in range(iterations):
            random_group = np.random.choice(params, group_size)
            for random_params in random_group:
                model, ratio = self.fit_model(random_params)
                models.append([random_params, ratio])

            if verbose >= 1:
                print('{:.4f}'.format((iteration+1)/iterations), end = '\r')

        sorted_models = [[x[0], x[1]] for x in sorted(models, key = lambda x: x[1])]
        self.best_model = sorted_models[-1]
        return self.best_model[0], self.best_model[1]

    def genetic_search(self):
        pass 

    def create_pipeline(self):
        pass
    

In [33]:
MAX_DEPTH = 300

XGB_PARAMS = {'n_estimators ': [20 + i*40 for i in range(5)], 
                'learning_rate': [0.01 + 0.01*i for i in range(10)], 
                'max_depth': [3 + i*30 for i in range(int((MAX_DEPTH - 3)/30))], 
                'subsample': [0.8 + i*0.05 for i in range(4)], 
                'colsample_bytree': [0.3 + i*0.05 for i in range(14)],
                'gamma': [0, 1, 5],
                'verbosity': [0]}

X = deepcopy(real_data_df.drop(columns = ['device_1']))
y = deepcopy(real_data_df['device_1'])


In [34]:
automl = AutoML(XGBClassifier, X, y, XGB_PARAMS, f1_score)

In [37]:
random_search_best_params,  = automl.random_search()

({&#39;n_estimators &#39;: 20,
  &#39;learning_rate&#39;: 0.09999999999999999,
  &#39;max_depth&#39;: 183,
  &#39;subsample&#39;: 0.9,
  &#39;colsample_bytree&#39;: 0.6000000000000001,
  &#39;gamma&#39;: 5,
  &#39;verbosity&#39;: 0},
 0.9986541049798116)