In [2]:
import requests
import pandas as pd 
import numpy as np
from copy import deepcopy

In [3]:
data = requests.get('https://b718b51c1217.ngrok.io/data/10000/6ytwk4ivTB7QkmlL0QPA1HNQ7NCOAb6Y').json()
data.keys()

dict_keys([&#39;room_Jan&#39;, &#39;room_Jan_synchronized&#39;, &#39;external_sensors&#39;])

In [4]:
real_data_df = pd.DataFrame(data['room_Jan'])

In [5]:
# During the analysis I didn't know which column represents sensors, and which represents devices. 
# That is why I have performed some data analysis to determine it. Also all sensors values have been 
# standarized, so that machine learning algorithms can converge easly to global minimum of 
# cost function. 

In [6]:
columns = deepcopy(real_data_df.columns)

In [7]:
print(real_data_df[columns[0]].describe())
real_data_df[columns[0]].unique()
# strings representing date, primary key of each table in the smarthouse project database

count                        10000
unique                       10000
top       Wed Sep 30 17:50:43 2020
freq                             1
Name: date, dtype: object


array([&#39;Tue Oct  6 10:07:28 2020&#39;, &#39;Tue Oct  6 10:07:48 2020&#39;,
       &#39;Tue Oct  6 10:08:08 2020&#39;, ..., &#39;Wed Sep 30 23:59:06 2020&#39;,
       &#39;Wed Sep 30 23:59:26 2020&#39;, &#39;Wed Sep 30 23:59:46 2020&#39;],
      dtype=object)

In [8]:
print(real_data_df[columns[1]].describe())
real_data_df[columns[1]].unique()
# values between 0.0 and 0.65, it is probably light sensor

count    10000.000000
mean         0.245638
std          0.222853
min          0.000000
25%          0.000000
50%          0.240000
75%          0.460000
max          0.640000
Name: sensor_light, dtype: float64


array([0.4 , 0.39, 0.41, 0.42, 0.47, 0.46, 0.45, 0.44, 0.43, 0.48, 0.49,
       0.5 , 0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ,
       0.38, 0.37, 0.35, 0.36, 0.34, 0.33, 0.32, 0.31, 0.3 , 0.29, 0.28,
       0.27, 0.26, 0.25, 0.24, 0.23, 0.22, 0.21, 0.2 , 0.  , 0.14, 0.03,
       0.12, 0.11, 0.16, 0.06, 0.1 , 0.17, 0.18, 0.15, 0.04, 0.09, 0.07,
       0.08, 0.01, 0.19, 0.13, 0.05, 0.02, 0.61, 0.62, 0.63, 0.64])

In [9]:
print(real_data_df[columns[2]].describe())
real_data_df[columns[2]].unique()
# real values between 0 and 22.1, also some 'nan' included, probably it is temperature sensor

count     10000.0
unique       48.0
top          20.8
freq       1124.0
Name: sensor_temperature, dtype: float64


array([21.8, 21.9, 22, 22.1, &#39;nan&#39;, 22.2, 22.3, 22.4, 19.4, 19.5, 19.6,
       19.7, 19.8, 19.9, 20, 20.1, 20.2, 20.3, 20.4, 20.5, 20.6, 20.7,
       20.8, 20.9, 21, 21.1, 21.2, 19.2, 19.1, 19, 18.8, 18.7, 18.6, 18.4,
       18.3, 18.2, 18.1, 18, 17.9, 17.8, 18.5, 18.9, 19.3, 21.3, 21.4,
       21.5, 21.6, 21.7], dtype=object)

In [10]:
print(real_data_df[columns[3]].describe())
real_data_df[columns[3]].unique()
# only zeros and ones, it is controllable divice

count    10000.000000
mean         0.213100
std          0.409518
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: sensor_desktop, dtype: float64


array([0, 1], dtype=int64)

In [11]:
print(real_data_df[columns[4]].describe())
real_data_df[columns[4]].unique()
# only zeros and ones, it is controllable divice

count    10000.000000
mean         0.578300
std          0.493856
min          0.000000
25%          0.000000
50%          1.000000
75%          1.000000
max          1.000000
Name: device_blinds, dtype: float64


array([1, 0], dtype=int64)

In [12]:
print(real_data_df[columns[5]].describe())
real_data_df[columns[5]].unique()
# only zeros and ones, it is controllable divice

count    10000.000000
mean         0.111800
std          0.315136
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: device_lamp, dtype: float64


array([0, 1], dtype=int64)

In [13]:
#real_data_df.columns = ['date', 'sensor_1', 'sensor_2', 'device_1', 'device_2', 'device_3']
real_data_df.index = real_data_df['date']
real_data_df = real_data_df.drop(columns = ['date'])

In [14]:
real_data_df

sensor_light sensor_temperature  sensor_desktop  \
date                                                                        
Tue Oct  6 10:07:28 2020          0.40               21.8               0   
Tue Oct  6 10:07:48 2020          0.40               21.8               0   
Tue Oct  6 10:08:08 2020          0.40               21.8               0   
Tue Oct  6 10:08:28 2020          0.40               21.8               0   
Tue Oct  6 10:08:48 2020          0.40               21.8               0   
...                                ...                ...             ...   
Wed Sep 30 23:58:26 2020          0.23               21.8               1   
Wed Sep 30 23:58:46 2020          0.23               21.9               1   
Wed Sep 30 23:59:06 2020          0.23               21.8               1   
Wed Sep 30 23:59:26 2020          0.23               21.8               1   
Wed Sep 30 23:59:46 2020          0.23               21.9               1   

                          device_blinds  device_lamp  
date                                                  
Tue Oct  6 10:07:28 2020              1            0  
Tue Oct  6 10:07:48 2020              1            0  
Tue Oct  6 10:08:08 2020              1            0  
Tue Oct  6 10:08:28 2020              1            0  
Tue Oct  6 10:08:48 2020              1            0  
...                                 ...          ...  
Wed Sep 30 23:58:26 2020              0            1  
Wed Sep 30 23:58:46 2020              0            1  
Wed Sep 30 23:59:06 2020              0            1  
Wed Sep 30 23:59:26 2020              0            1  
Wed Sep 30 23:59:46 2020              0            1  

[10000 rows x 5 columns]

In [15]:
# Next step is to determine best rule indiction algorithm. Our goal is to find a rule 
# of behaviours between devices and sensors, so that our algorithm can predict properly when it should
# activate each device. 2 algorithms I am going to compare are Decision Trees, Random Forest and Extreeme Gradient Boosted Trees.

In [16]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn import metrics

from copy import deepcopy
import itertools

In [17]:
from sklearn.metrics import fbeta_score

def f1_score(y_true, y_pred, threshold = 0.5):
    y_pred_class = y_pred >= threshold
    y_true = y_true == 1
    return fbeta_score(y_true, y_pred_class, beta = 1)

In [18]:
class AutoTuningHyperparameters(object):
    @staticmethod
    def standarize(X, standarization_rule = None):
        data = deepcopy(X.replace(['nan'], 0))
        for column_name in data.columns:
            if 'sensor' in column_name:
                data[column_name] = (data[column_name] - data[column_name].mean())/data[column_name].std()
        return data

    @staticmethod
    def generate_all_possible_params(params):
        params_unpacked = {key: list(np.arange(params[key][0], params[key][1] + params[key][2], params[key][2])) for key in                     params.keys()}
        keys, values = zip(*params_unpacked.items())
        possible_params = [dict(zip(keys, v)) for v in itertools.product(*values)]
        return possible_params

    def __init__(self, model, X, y, params, cost):
        self.model = model 
        X = self.standarize(X) 
        self.X_train = X[:int(0.7*len(X))]
        self.X_test = X[int(0.7*len(X)):]
        self.y_train = y[:int(0.7*len(y))]
        self.y_test = y[int(0.7*len(y)):]
        self.params = params
        self.cost = cost
        self.best_model = None
    
    def fit_model(self, params):
        model = self.model(**params)
        try:
            model.fit(self.X_train, self.y_train)
            predictions = model.predict(self.X_test)
            return model, self.cost(self.y_test, predictions)
        except:
            return None, 0
    
    def grid_search(self, params = None, verbose = 1):
        if params:
            params = self.generate_all_possible_params(params)
        else:
            params = self.generate_all_possible_params(self.params)
        models = []
        for index, parameters in enumerate(params):
            model, ratio = self.fit_model(parameters)
            models.append([parameters, ratio])

            if verbose >= 1:
                print('{:.4f}'.format((index+1)/len(params)), end = '\r')

        sorted_models = [[x[0], x[1]] for x in sorted(models, key = lambda x: x[1])]
        self.best_model = sorted_models[-1]
        return self.best_model[0], self.best_model[1]

    def random_search(self, verbose = 1, group_size = 5, iterations = 20, params = None):
        if params:
            params = self.generate_all_possible_params(params)
        else:
            params = self.generate_all_possible_params(self.params)

        models = []
        for iteration in range(iterations):
            random_group = np.random.choice(params, group_size)
            for random_params in random_group:
                model, ratio = self.fit_model(random_params)
                models.append([random_params, ratio])

            if verbose >= 1:
                print('{:.4f}'.format((iteration+1)/iterations), end = '\r')

        sorted_models = [[x[0], x[1]] for x in sorted(models, key = lambda x: x[1])]
        self.best_model = sorted_models[-1]
        return self.best_model[0], self.best_model[1]

    def genetic_search(self):
        pass 

    def auto_tune_pipeline(self, pipeline = ['random', 'grid'], narrow_to = 0.2, params = None):
        if params:
            params = params
        else:
            params = self.params
        
        possible_params_lengths = {key: len([param for param in np.arange(params[key][0], params[key][1], params[key][2])]) for key in list(params.keys())}

        for search in pipeline:
            if search == 'random':
                best_params, score = self.random_search(params = params, group_size = 5, iterations = 50)
            elif search == 'grid':
                best_params, score = self.random_search(params = params)


            for key in best_params.keys():
                key_type = type(params[key][2])
                params_length = possible_params_lengths[key]
                new_min = key_type(best_params[key] - key_type(narrow_to * params_length) * params[key][2])
                new_max = key_type(best_params[key] + key_type(narrow_to * params_length) * params[key][2])
                if new_min > params[key][0]:
                    params[key][0] = new_min
                if new_max < params[key][1]:
                    params[key][1] = new_max
            print('new search ranges for parameters: {}'.format(params))

            print('performed {} serach with max score of {} and best parameters {}'.format(search, score, best_params))

        return best_params, score


    

In [19]:
real_data_df.columns

Index([&#39;sensor_light&#39;, &#39;sensor_temperature&#39;, &#39;sensor_desktop&#39;, &#39;device_blinds&#39;,
       &#39;device_lamp&#39;],
      dtype=&#39;object&#39;)

In [20]:
XGB_PARAMS = {'n_estimators ': [20, 300, 20], 
                'learning_rate': [0.01, 0.1, 0.01], 
                'max_depth': [3, 300, 30], 
                'subsample': [0.8, 1, 0.05], 
                'colsample_bytree': [0.3, 0.8, 0.05],
                'gamma': [0, 5, 1],
                'verbosity': [0, 0, 1]}

X = deepcopy(real_data_df.drop(columns = ['device_blinds']))
y = deepcopy(real_data_df['device_blinds'])


In [21]:
# params = {'n_estimators ': [1, 50, 1], 
#                 'learning_rate': [5, 15, 5], 
#                 'max_depth': [0.01, 0.1, 0.01]}
# params_unpacked = {key: list(np.arange(params[key][0], params[key][1] + params[key][2], params[key][2])) for key in params.keys()}
# params_unpacked


In [22]:
automl = AutoTuningHyperparameters(XGBClassifier, X, y, XGB_PARAMS, f1_score)

In [23]:
# automl pipeline

In [24]:
best_params, score = automl.auto_tune_pipeline()


new search ranges for parameters: {&#39;n_estimators &#39;: [80, 160, 20], &#39;learning_rate&#39;: [0.01, 0.028000000000000004, 0.01], &#39;max_depth&#39;: [93, 213, 30], &#39;subsample&#39;: [0.9600000000000002, 1, 0.05], &#39;colsample_bytree&#39;: [0.6499999999999999, 0.8, 0.05], &#39;gamma&#39;: [3, 5, 1], &#39;verbosity&#39;: [0, 0, 1]}
performed random serach with max score of 0.8148667601683028 and best parameters {&#39;n_estimators &#39;: 120, &#39;learning_rate&#39;: 0.01, &#39;max_depth&#39;: 153, &#39;subsample&#39;: 1.0000000000000002, &#39;colsample_bytree&#39;: 0.7499999999999999, &#39;gamma&#39;: 4, &#39;verbosity&#39;: 0}
new search ranges for parameters: {&#39;n_estimators &#39;: [80, 160, 20], &#39;learning_rate&#39;: [0.01, 0.028000000000000004, 0.01], &#39;max_depth&#39;: [93, 183, 30], &#39;subsample&#39;: [0.9600000000000002, 1, 0.05], &#39;colsample_bytree&#39;: [0.7000000000000001, 0.8, 0.05], &#39;gamma&#39;: [3, 5, 1], &#39;verbosity&#39;: [0, 0, 1]}
performe

In [25]:
best_params


{&#39;n_estimators &#39;: 120,
 &#39;learning_rate&#39;: 0.01,
 &#39;max_depth&#39;: 123,
 &#39;subsample&#39;: 0.9600000000000002,
 &#39;colsample_bytree&#39;: 0.8,
 &#39;gamma&#39;: 4,
 &#39;verbosity&#39;: 0}

In [26]:
# Next thing that is needed for this project is data preprocessing module. During the analysis I had to analyse data only from one  device. Unfortunately, this is not the case in real life iot system. We can have lots of devices, sending data in not parallel time (ex. varying in one second). Preprocessing module should be able to properly create array of data, with properly standarized features, and joined tables from dfferent devices. Also, as the data is in form of time series, it should be properly batched and padded.

In [30]:
data_dfs = [pd.DataFrame(data[key]) for key in list(data.keys())[1:]]

In [43]:
copy_df_1 = deepcopy(data_dfs[0])
copy_df_1['date'] = pd.to_datetime(copy_df_1['date'])
copy_df_1

date  sensor_light sensor_temperature  sensor_desktop  \
0    2020-10-06 17:54:00          0.51               22.4               1   
1    2020-10-06 17:54:20          0.50               22.5               1   
2    2020-10-06 17:54:40          0.50               22.5               1   
3    2020-10-06 17:55:00          0.49               22.5               1   
4    2020-10-06 17:55:20          0.49               22.5               1   
...                  ...           ...                ...             ...   
2646 2020-10-07 08:42:00          0.48               22.1               0   
2647 2020-10-07 08:42:20          0.47               22.1               0   
2648 2020-10-07 08:42:39          0.47               22.1               0   
2649 2020-10-07 08:42:59          0.47               22.1               0   
2650 2020-10-07 08:43:19          0.47               22.1               0   

      device_blinds  device_lamp  
0                 1            0  
1                 1            0  
2                 1            0  
3                 1            0  
4                 1            0  
...             ...          ...  
2646              1            0  
2647              1            0  
2648              1            0  
2649              1            0  
2650              1            0  

[2651 rows x 6 columns]

In [44]:
copy_df_2 = deepcopy(data_dfs[1])
copy_df_2['date'] = pd.to_datetime(copy_df_2['date'])
copy_df_2

date  sensor_light
0    2020-10-06 19:12:40          0.00
1    2020-10-06 19:17:01          0.00
2    2020-10-06 19:17:21          0.00
3    2020-10-06 19:17:40          0.00
4    2020-10-06 19:18:00          0.00
...                  ...           ...
2411 2020-10-07 08:42:00          0.75
2412 2020-10-07 08:42:20          0.75
2413 2020-10-07 08:42:40          0.75
2414 2020-10-07 08:43:00          0.75
2415 2020-10-07 08:43:20          0.75

[2416 rows x 2 columns]

In [56]:
pd.merge_asof(copy_df_1, copy_df_2, on = "date", tolerance=pd.Timedelta('5s'), direction='backward', suffixes = ['_' + key for key in list(data.keys())[1:]])[300:350]

date  sensor_light_room_Jan_synchronized  \
300 2020-10-06 19:37:40                                0.49   
301 2020-10-06 19:38:00                                0.49   
302 2020-10-06 19:38:20                                0.49   
303 2020-10-06 19:38:40                                0.49   
304 2020-10-06 19:39:00                                0.49   
305 2020-10-06 19:39:20                                0.49   
306 2020-10-06 19:39:40                                0.49   
307 2020-10-06 19:40:00                                0.49   
308 2020-10-06 19:40:20                                0.49   
309 2020-10-06 19:40:40                                0.49   
310 2020-10-06 19:41:00                                0.49   
311 2020-10-06 19:41:20                                0.49   
312 2020-10-06 19:41:40                                0.49   
313 2020-10-06 19:42:00                                0.49   
314 2020-10-06 19:42:20                                0.49   
315 2020-10-06 19:42:40                                0.49   
316 2020-10-06 19:43:00                                0.49   
317 2020-10-06 19:43:20                                0.49   
318 2020-10-06 19:43:40                                0.49   
319 2020-10-06 19:44:00                                0.49   
320 2020-10-06 19:44:20                                0.49   
321 2020-10-06 19:44:40                                0.49   
322 2020-10-06 19:45:00                                0.49   
323 2020-10-06 19:45:21                                0.49   
324 2020-10-06 19:45:40                                0.49   
325 2020-10-06 19:46:00                                0.49   
326 2020-10-06 19:46:21                                0.49   
327 2020-10-06 19:46:41                                0.49   
328 2020-10-06 19:47:01                                0.49   
329 2020-10-06 19:47:21                                0.49   
330 2020-10-06 19:47:40                                0.49   
331 2020-10-06 19:48:00                                0.49   
332 2020-10-06 19:48:21                                0.49   
333 2020-10-06 19:48:41                                0.49   
334 2020-10-06 19:49:01                                0.49   
335 2020-10-06 19:49:20                                0.49   
336 2020-10-06 19:49:40                                0.49   
337 2020-10-06 19:50:00                                0.49   
338 2020-10-06 19:50:20                                0.49   
339 2020-10-06 19:50:40                                0.49   
340 2020-10-06 19:51:00                                0.49   
341 2020-10-06 19:51:20                                0.49   
342 2020-10-06 19:51:40                                0.49   
343 2020-10-06 19:52:00                                0.49   
344 2020-10-06 19:52:20                                0.49   
345 2020-10-06 19:52:40                                0.49   
346 2020-10-06 19:53:00                                0.49   
347 2020-10-06 19:53:20                                0.49   
348 2020-10-06 19:53:40                                0.49   
349 2020-10-06 19:54:00                                0.49   

    sensor_temperature  sensor_desktop  device_blinds  device_lamp  \
300               22.4               1              0            1   
301               22.4               1              0            1   
302               22.4               1              0            1   
303               22.4               1              0            1   
304               22.4               1              0            1   
305               22.5               1              0            1   
306               22.5               1              0            1   
307               22.5               1              0            1   
308               22.5               1              0            1   
309               22.5               1              0            1   
310               22.5             

In [111]:
class PreprocessData(object):
    def __init__(self, data, standarization_rule = 'sensor', tolerance=pd.Timedelta('5s'), nan_value = -1):
        data_dfs = [pd.DataFrame(data[key]) for key in list(data.keys())]
        for data_df_index in range(len(data_dfs)):
            data_dfs[data_df_index]['date'] = pd.to_datetime(data_dfs[data_df_index]['date'])
            data_dfs[data_df_index] = data_dfs[data_df_index].sort_values(by='date')

        for data_df_index in range(len(data_dfs[:-1])):
            data_dfs[data_df_index + 1] = pd.merge_asof(data_dfs[data_df_index], data_dfs[data_df_index + 1], on = "date", tolerance=tolerance, direction='backward', suffixes = ['_' + key for key in list                                                 (data.keys())[data_df_index:data_df_index+2]]).fillna(nan_value)

        self.data_df = data_dfs[-1]



In [112]:
data_preprocessor = PreprocessData({key: data[key] for key in list(data.keys())[1:]})

In [113]:
data_preprocessor.data_df

date  sensor_light_room_Jan_synchronized  \
0    2020-10-06 17:54:00                                0.51   
1    2020-10-06 17:54:20                                0.50   
2    2020-10-06 17:54:40                                0.50   
3    2020-10-06 17:55:00                                0.49   
4    2020-10-06 17:55:20                                0.49   
...                  ...                                 ...   
2646 2020-10-07 08:42:00                                0.48   
2647 2020-10-07 08:42:20                                0.47   
2648 2020-10-07 08:42:39                                0.47   
2649 2020-10-07 08:42:59                                0.47   
2650 2020-10-07 08:43:19                                0.47   

     sensor_temperature  sensor_desktop  device_blinds  device_lamp  \
0                  22.4               1              1            0   
1                  22.5               1              1            0   
2                  22.5               1              1            0   
3                  22.5               1              1            0   
4                  22.5               1              1            0   
...                 ...             ...            ...          ...   
2646               22.1               0              1            0   
2647               22.1               0              1            0   
2648               22.1               0              1            0   
2649               22.1               0              1            0   
2650               22.1               0              1            0   

      sensor_light_external_sensors  
0                             -1.00  
1                             -1.00  
2                             -1.00  
3                             -1.00  
4                             -1.00  
...                             ...  
2646                           0.75  
2647                           0.75  
2648                          -1.00  
2649                          -1.00  
2650                          -1.00  

[2651 rows x 7 columns]