In [1]:
import requests
import pandas as pd 
import numpy as np

In [3]:
data = requests.get('https://d946a72959ed.ngrok.io/data/6ytwk4ivTB7QkmlL0QPA1HNQ7NCOAb6Y').json()
data.keys()

dict_keys([&#39;room_Jan&#39;])

In [4]:
real_data_df = pd.DataFrame(data['room_Jan'])

In [5]:
# During the analysis I didn't know which column represents sensors, and which represents devices. 
# That is why I have performed some data analysis to determine it. Also all sensors values have been 
# standarized, so that machine learning algorithms can converge easly to global minimum of 
# cost function. 

In [6]:
print(real_data_df[0].describe())
real_data_df[0].unique()
# strings representing date, primary key of each table in the smarthouse project database

count                          272
unique                         272
top       Sat Oct  3 15:28:32 2020
freq                             1
Name: 0, dtype: object


array([&#39;Sat Oct  3 14:02:15 2020&#39;, &#39;Sat Oct  3 14:02:35 2020&#39;,
       &#39;Sat Oct  3 14:02:55 2020&#39;, &#39;Sat Oct  3 14:03:15 2020&#39;,
       &#39;Sat Oct  3 14:03:35 2020&#39;, &#39;Sat Oct  3 14:03:55 2020&#39;,
       &#39;Sat Oct  3 14:04:15 2020&#39;, &#39;Sat Oct  3 14:04:35 2020&#39;,
       &#39;Sat Oct  3 14:04:55 2020&#39;, &#39;Sat Oct  3 14:05:15 2020&#39;,
       &#39;Sat Oct  3 14:05:35 2020&#39;, &#39;Sat Oct  3 14:05:55 2020&#39;,
       &#39;Sat Oct  3 14:06:15 2020&#39;, &#39;Sat Oct  3 14:06:36 2020&#39;,
       &#39;Sat Oct  3 14:06:56 2020&#39;, &#39;Sat Oct  3 14:07:16 2020&#39;,
       &#39;Sat Oct  3 14:07:36 2020&#39;, &#39;Sat Oct  3 14:07:56 2020&#39;,
       &#39;Sat Oct  3 14:08:16 2020&#39;, &#39;Sat Oct  3 14:08:36 2020&#39;,
       &#39;Sat Oct  3 14:08:56 2020&#39;, &#39;Sat Oct  3 14:09:16 2020&#39;,
       &#39;Sat Oct  3 14:09:36 2020&#39;, &#39;Sat Oct  3 14:09:56 2020&#39;,
       &#39;Sat Oct  3 14:10:16 2020&#39;, &#39;Sat 

In [7]:
print(real_data_df[1].describe())
real_data_df[1].unique()
# values between 0.0 and 0.65, it is probably light sensor

count    272.000000
mean       0.577390
std        0.060333
min        0.400000
25%        0.540000
50%        0.580000
75%        0.600000
max        0.790000
Name: 1, dtype: float64


array([0.59, 0.6 , 0.56, 0.63, 0.61, 0.57, 0.52, 0.58, 0.5 , 0.65, 0.62,
       0.51, 0.75, 0.4 , 0.53, 0.55, 0.54, 0.78, 0.74, 0.76, 0.68, 0.79,
       0.64, 0.71, 0.48, 0.73, 0.72, 0.77, 0.44, 0.42, 0.67, 0.49, 0.47,
       0.45])

In [8]:
print(real_data_df[2].describe())
real_data_df[2].unique()
# real values between 0 and 22.1, also some 'nan' included, probably it is temperature sensor

count     272.0
unique      2.0
top        22.4
freq      271.0
Name: 2, dtype: float64


array([22.4, &#39;nan&#39;], dtype=object)

In [9]:
print(real_data_df[3].describe())
real_data_df[3].unique()
# only zeros and ones, it is controllable divice

count    272.0
mean       1.0
std        0.0
min        1.0
25%        1.0
50%        1.0
75%        1.0
max        1.0
Name: 3, dtype: float64


array([1], dtype=int64)

In [10]:
print(real_data_df[4].describe())
real_data_df[4].unique()
# only zeros and ones, it is controllable divice

count    272.0
mean       1.0
std        0.0
min        1.0
25%        1.0
50%        1.0
75%        1.0
max        1.0
Name: 4, dtype: float64


array([1], dtype=int64)

In [11]:
print(real_data_df[5].describe())
real_data_df[5].unique()
# only zeros and ones, it is controllable divice

count    272.0
mean       0.0
std        0.0
min        0.0
25%        0.0
50%        0.0
75%        0.0
max        0.0
Name: 5, dtype: float64


array([0], dtype=int64)

In [12]:
real_data_df.columns = ['date', 'sensor_1', 'sensor_2', 'device_1', 'device_2', 'device_3']
real_data_df.index = real_data_df['date']
real_data_df = real_data_df.drop(columns = ['date'])

In [13]:
real_data_df

sensor_1 sensor_2  device_1  device_2  device_3
date                                                                     
Sat Oct  3 14:02:15 2020      0.59     22.4         1         1         0
Sat Oct  3 14:02:35 2020      0.60     22.4         1         1         0
Sat Oct  3 14:02:55 2020      0.60     22.4         1         1         0
Sat Oct  3 14:03:15 2020      0.56     22.4         1         1         0
Sat Oct  3 14:03:35 2020      0.63     22.4         1         1         0
...                            ...      ...       ...       ...       ...
Sat Oct  3 15:31:12 2020      0.58     22.4         1         1         0
Sat Oct  3 15:31:32 2020      0.55     22.4         1         1         0
Sat Oct  3 15:31:52 2020      0.54     22.4         1         1         0
Sat Oct  3 15:32:12 2020      0.58     22.4         1         1         0
Sat Oct  3 15:32:32 2020      0.54     22.4         1         1         0

[272 rows x 5 columns]

In [14]:
# Next step is to determine best rule indiction algorithm. Our goal is to find a rule 
# of behaviours between devices and sensors, so that our algorithm can predict properly when it should
# activate each device. 2 algorithms I am going to compare are Decision Trees, Random Forest and Extreeme Gradient Boosted Trees.

In [16]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn import metrics

from copy import deepcopy
import itertools

In [17]:
from sklearn.metrics import fbeta_score

def f1_score(y_true, y_pred, threshold = 0.5):
    y_pred_class = y_pred >= threshold
    y_true = y_true == 1
    return fbeta_score(y_true, y_pred_class, beta = 1)

In [115]:
class AutoTuningHyperparameters(object):
    @staticmethod
    def standarize(X, standarization_rule = None):
        data = deepcopy(X.replace(['nan'], 0))
        for column_name in data.columns:
            if 'sensor' in column_name:
                data[column_name] = (data[column_name] - data[column_name].mean())/data[column_name].std()
        return data

    @staticmethod
    def generate_all_possible_params(params):
        params_unpacked = {key: list(np.arange(params[key][0], params[key][1] + params[key][2], params[key][2])) for key in                     params.keys()}
        keys, values = zip(*params_unpacked.items())
        possible_params = [dict(zip(keys, v)) for v in itertools.product(*values)]
        return possible_params

    def __init__(self, model, X, y, params, cost):
        self.model = model 
        X = self.standarize(X) 
        self.X_train = X[:int(0.7*len(X))]
        self.X_test = X[int(0.7*len(X)):]
        self.y_train = y[:int(0.7*len(y))]
        self.y_test = y[int(0.7*len(y)):]
        self.params = params
        self.cost = cost
        self.best_model = None
    
    def fit_model(self, params):
        model = self.model(**params)
        model.fit(self.X_train, self.y_train)
        predictions = model.predict(self.X_test)
        return model, self.cost(self.y_test, predictions)
    
    def grid_search(self, params = None, verbose = 1):
        if params:
            params = self.generate_all_possible_params(params)
        else:
            params = self.generate_all_possible_params(self.params)
        models = []
        for index, parameters in enumerate(params):
            model, ratio = self.fit_model(parameters)
            models.append([parameters, ratio])

            if verbose >= 1:
                print('{:.4f}'.format((index+1)/len(params)), end = '\r')

        sorted_models = [[x[0], x[1]] for x in sorted(models, key = lambda x: x[1])]
        self.best_model = sorted_models[-1]
        return self.best_model[0], self.best_model[1]

    def random_search(self, verbose = 1, group_size = 5, iterations = 20, params = None):
        if params:
            params = self.generate_all_possible_params(params)
        else:
            params = self.generate_all_possible_params(self.params)

        models = []
        for iteration in range(iterations):
            random_group = np.random.choice(params, group_size)
            for random_params in random_group:
                model, ratio = self.fit_model(random_params)
                models.append([random_params, ratio])

            if verbose >= 1:
                print('{:.4f}'.format((iteration+1)/iterations), end = '\r')

        sorted_models = [[x[0], x[1]] for x in sorted(models, key = lambda x: x[1])]
        self.best_model = sorted_models[-1]
        return self.best_model[0], self.best_model[1]

    def genetic_search(self):
        pass 

    def auto_tune_pipeline(self, pipeline = ['random', 'grid'], narrow_to = 0.2, params = None):
        if params:
            params = params
        else:
            params = self.params
        
        for search in pipeline:
            if search == 'random':
                best_params, score = self.random_search(params = params, group_size = 10, iterations = 50)
            elif search == 'grid':
                best_params, score = self.random_search(params = params)

            for key in best_params.keys():
                key_type = type(params[key][2])
                new_min = key_type(best_params[key] - narrow_to * best_params[key])
                new_max = key_type(best_params[key] + narrow_to * best_params[key])
                if new_min > params[key][0]:
                    params[key][0] = new_min
                if new_max < params[key][1]:
                    params[key][1] = new_max

            print('performed {} serach with max score of {} and best parameters {}'.format(search, score, best_params))

        return best_params, score


    

In [116]:
XGB_PARAMS = {'n_estimators ': [20, 300, 20], 
                'learning_rate': [0.01, 0.1, 0.01], 
                'max_depth': [3, 300, 30], 
                'subsample': [0.8, 1, 0.05], 
                'colsample_bytree': [0.3, 0.8, 0.05],
                'gamma': [0, 5, 1],
                'verbosity': [0, 0, 1]}

X = deepcopy(real_data_df.drop(columns = ['device_1']))
y = deepcopy(real_data_df['device_1'])


In [117]:
# params = {'n_estimators ': [1, 50, 1], 
#                 'learning_rate': [5, 15, 5], 
#                 'max_depth': [0.01, 0.1, 0.01]}
# params_unpacked = {key: list(np.arange(params[key][0], params[key][1] + params[key][2], params[key][2])) for key in params.keys()}
# params_unpacked


In [118]:
automl = AutoTuningHyperparameters(XGBClassifier, X, y, XGB_PARAMS, f1_score)

In [119]:
# automl pipeline

In [120]:
best_params, score = automl.auto_tune_pipeline()


performed random serach with max score of 1.0 and best parameters {&#39;n_estimators &#39;: 220, &#39;learning_rate&#39;: 0.06999999999999999, &#39;max_depth&#39;: 273, &#39;subsample&#39;: 0.9500000000000002, &#39;colsample_bytree&#39;: 0.7, &#39;gamma&#39;: 4, &#39;verbosity&#39;: 0}
performed grid serach with max score of 1.0 and best parameters {&#39;n_estimators &#39;: 236, &#39;learning_rate&#39;: 0.08599999999999998, &#39;max_depth&#39;: 278, &#39;subsample&#39;: 1.0000000000000002, &#39;colsample_bytree&#39;: 0.66, &#39;gamma&#39;: 3, &#39;verbosity&#39;: 0}


In [121]:
best_params


{&#39;n_estimators &#39;: 236,
 &#39;learning_rate&#39;: 0.08599999999999998,
 &#39;max_depth&#39;: 278,
 &#39;subsample&#39;: 1.0000000000000002,
 &#39;colsample_bytree&#39;: 0.66,
 &#39;gamma&#39;: 3,
 &#39;verbosity&#39;: 0}

In [95]:
random_search_best_params

{&#39;n_estimators &#39;: 280,
 &#39;learning_rate&#39;: 0.03,
 &#39;max_depth&#39;: 183,
 &#39;subsample&#39;: 1.0000000000000002,
 &#39;colsample_bytree&#39;: 0.7999999999999998,
 &#39;gamma&#39;: 0,
 &#39;verbosity&#39;: 0}