In [1]:
import requests
import pandas as pd 
import numpy as np
from copy import deepcopy

In [2]:
data = requests.get('https://e5a2995573e6.ngrok.io/data/10000/6ytwk4ivTB7QkmlL0QPA1HNQ7NCOAb6Y').json()
data.keys()

dict_keys(['room_Jan', 'room_Jan_synchronized', 'external_sensors'])

In [3]:
real_data_df = pd.DataFrame(data['room_Jan'])

In [4]:
# During the analysis I didn't know which column represents sensors, and which represents devices. 
# That is why I have performed some data analysis to determine it. Also all sensors values have been 
# standarized, so that machine learning algorithms can converge easly to global minimum of 
# cost function. 

In [5]:
columns = deepcopy(real_data_df.columns)

In [6]:
print(real_data_df[columns[0]].describe())
real_data_df[columns[0]].unique()
# strings representing date, primary key of each table in the smarthouse project database

count                          400
unique                         400
top       Sat Oct  3 15:29:12 2020
freq                             1
Name: date, dtype: object


array(['Sat Oct  3 14:02:15 2020', 'Sat Oct  3 14:02:35 2020',
       'Sat Oct  3 14:02:55 2020', 'Sat Oct  3 14:03:15 2020',
       'Sat Oct  3 14:03:35 2020', 'Sat Oct  3 14:03:55 2020',
       'Sat Oct  3 14:04:15 2020', 'Sat Oct  3 14:04:35 2020',
       'Sat Oct  3 14:04:55 2020', 'Sat Oct  3 14:05:15 2020',
       'Sat Oct  3 14:05:35 2020', 'Sat Oct  3 14:05:55 2020',
       'Sat Oct  3 14:06:15 2020', 'Sat Oct  3 14:06:36 2020',
       'Sat Oct  3 14:06:56 2020', 'Sat Oct  3 14:07:16 2020',
       'Sat Oct  3 14:07:36 2020', 'Sat Oct  3 14:07:56 2020',
       'Sat Oct  3 14:08:16 2020', 'Sat Oct  3 14:08:36 2020',
       'Sat Oct  3 14:08:56 2020', 'Sat Oct  3 14:09:16 2020',
       'Sat Oct  3 14:09:36 2020', 'Sat Oct  3 14:09:56 2020',
       'Sat Oct  3 14:10:16 2020', 'Sat Oct  3 14:10:36 2020',
       'Sat Oct  3 14:10:56 2020', 'Sat Oct  3 14:11:17 2020',
       'Sat Oct  3 14:11:37 2020', 'Sat Oct  3 14:11:57 2020',
       'Sat Oct  3 14:12:17 2020', 'Sat Oct  3 14:12:37

In [7]:
print(real_data_df[columns[1]].describe())
real_data_df[columns[1]].unique()
# values between 0.0 and 0.65, it is probably light sensor

count    400.000000
mean       0.541400
std        0.118159
min        0.050000
25%        0.520000
50%        0.560000
75%        0.600000
max        0.790000
Name: sensor_light, dtype: float64


array([0.59, 0.6 , 0.56, 0.63, 0.61, 0.57, 0.52, 0.58, 0.5 , 0.65, 0.62,
       0.51, 0.75, 0.4 , 0.53, 0.55, 0.54, 0.78, 0.74, 0.76, 0.68, 0.79,
       0.64, 0.71, 0.48, 0.73, 0.72, 0.77, 0.44, 0.42, 0.67, 0.49, 0.47,
       0.45, 0.46, 0.69, 0.43, 0.66, 0.25, 0.15, 0.14, 0.13, 0.12, 0.11,
       0.1 , 0.09, 0.08, 0.07, 0.06, 0.05])

In [8]:
print(real_data_df[columns[2]].describe())
real_data_df[columns[2]].unique()
# real values between 0 and 22.1, also some 'nan' included, probably it is temperature sensor

count     400.0
unique      4.0
top        22.4
freq      294.0
Name: sensor_temperature, dtype: float64


array([22.4, 'nan', 22.5, 22.6], dtype=object)

In [9]:
print(real_data_df[columns[3]].describe())
real_data_df[columns[3]].unique()
# only zeros and ones, it is controllable divice

count    400.000000
mean       0.780000
std        0.414765
min        0.000000
25%        1.000000
50%        1.000000
75%        1.000000
max        1.000000
Name: sensor_desktop, dtype: float64


array([1, 0], dtype=int64)

In [10]:
print(real_data_df[columns[4]].describe())
real_data_df[columns[4]].unique()
# only zeros and ones, it is controllable divice

count    400.0
mean       1.0
std        0.0
min        1.0
25%        1.0
50%        1.0
75%        1.0
max        1.0
Name: device_blinds, dtype: float64


array([1], dtype=int64)

In [11]:
print(real_data_df[columns[5]].describe())
real_data_df[columns[5]].unique()
# only zeros and ones, it is controllable divice

count    400.0
mean       0.0
std        0.0
min        0.0
25%        0.0
50%        0.0
75%        0.0
max        0.0
Name: device_lamp, dtype: float64


array([0], dtype=int64)

In [12]:
#real_data_df.columns = ['date', 'sensor_1', 'sensor_2', 'device_1', 'device_2', 'device_3']
real_data_df.index = real_data_df['date']
real_data_df = real_data_df.drop(columns = ['date'])

In [13]:
real_data_df

sensor_light sensor_temperature  sensor_desktop  \
date                                                                        
Sat Oct  3 14:02:15 2020          0.59               22.4               1   
Sat Oct  3 14:02:35 2020          0.60               22.4               1   
Sat Oct  3 14:02:55 2020          0.60               22.4               1   
Sat Oct  3 14:03:15 2020          0.56               22.4               1   
Sat Oct  3 14:03:35 2020          0.63               22.4               1   
...                                ...                ...             ...   
Sat Oct  3 18:10:04 2020          0.06               22.5               1   
Sat Oct  3 18:10:24 2020          0.06               22.5               1   
Sat Oct  3 18:10:44 2020          0.06               22.6               1   
Sat Oct  3 18:11:04 2020          0.05               22.5               1   
Sat Oct  3 18:11:24 2020          0.05               22.5               1   

                          device_blinds  device_lamp  
date                                                  
Sat Oct  3 14:02:15 2020              1            0  
Sat Oct  3 14:02:35 2020              1            0  
Sat Oct  3 14:02:55 2020              1            0  
Sat Oct  3 14:03:15 2020              1            0  
Sat Oct  3 14:03:35 2020              1            0  
...                                 ...          ...  
Sat Oct  3 18:10:04 2020              1            0  
Sat Oct  3 18:10:24 2020              1            0  
Sat Oct  3 18:10:44 2020              1            0  
Sat Oct  3 18:11:04 2020              1            0  
Sat Oct  3 18:11:24 2020              1            0  

[400 rows x 5 columns]

In [14]:
# Next step is to determine best rule indiction algorithm. Our goal is to find a rule 
# of behaviours between devices and sensors, so that our algorithm can predict properly when it should
# activate each device. 2 algorithms I am going to compare are Decision Trees, Random Forest and Extreeme Gradient Boosted Trees.

In [15]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn import metrics

from copy import deepcopy
import itertools

In [16]:
from sklearn.metrics import fbeta_score

def f1_score(y_true, y_pred, threshold = 0.5):
    y_pred_class = y_pred >= threshold
    y_true = y_true == 1
    return fbeta_score(y_true, y_pred_class, beta = 1)

In [17]:
class AutoTuningHyperparameters(object):
    # @staticmethod
    # def standarize(X, standarization_rule = 'sensor'):
    #     data = deepcopy(X.replace(['nan'], 0))
    #     for column_name in data.columns:
    #         if standarization_rule in column_name:
    #             data[column_name] = (data[column_name] - data[column_name].mean())/data[column_name].std()
    #     return data

    @staticmethod
    def generate_all_possible_params(params):
        
        params_unpacked = {key: list(np.arange(params[key][0], params[key][1] + params[key][2], params[key][2])) for key in                     params.keys()}
        keys, values = zip(*params_unpacked.items())
        possible_params = [dict(zip(keys, v)) for v in itertools.product(*values)]
        return possible_params

    def __init__(self, model, X, y, params, cost):
        self.model = model 
        # X = self.standarize(X) 
        self.X_train = X[:int(0.7*len(X))]
        self.X_test = X[int(0.7*len(X)):]
        self.y_train = y[:int(0.7*len(y))]
        self.y_test = y[int(0.7*len(y)):]
        self.params = params
        self.cost = cost
        self.best_model = None
    
    def fit_model(self, params):
        model = self.model(**params)
        try:
            model.fit(self.X_train, self.y_train)
            predictions = model.predict(self.X_test)
            return model, self.cost(self.y_test, predictions)
        except Exception as e:
            print(e)
            return None, 0
    
    def grid_search(self, params = None, verbose = 1):
        if params:
            params = self.generate_all_possible_params(params)
        else:
            params = self.generate_all_possible_params(self.params)
        models = []
        for index, parameters in enumerate(params):
            model, ratio = self.fit_model(parameters)
            models.append([parameters, ratio])

            if verbose >= 1:
                print('{:.4f}'.format((index+1)/len(params)), end = '\r')

        sorted_models = [[x[0], x[1]] for x in sorted(models, key = lambda x: x[1])]
        self.best_model = sorted_models[-1]
        return self.best_model[0], self.best_model[1]

    def random_search(self, verbose = 1, group_size = 5, iterations = 20, params = None):
        if params:
            params = self.generate_all_possible_params(params)
        else:
            params = self.generate_all_possible_params(self.params)

        models = []
        for iteration in range(iterations):
            random_group = np.random.choice(params, group_size)
            for random_params in random_group:
                model, ratio = self.fit_model(random_params)
                models.append([random_params, ratio])

            if verbose >= 1:
                print('{:.4f}'.format((iteration+1)/iterations), end = '\r')

        sorted_models = [[x[0], x[1]] for x in sorted(models, key = lambda x: x[1])]
        self.best_model = sorted_models[-1]
        return self.best_model[0], self.best_model[1]

    def genetic_search(self):
        pass 

    def auto_tune_pipeline(self, pipeline = ['random', 'grid'], narrow_to = 0.2, params = None):
        if params:
            params = params
        else:
            params = self.params
        
        possible_params_lengths = {key: len([param for param in np.arange(params[key][0], params[key][1], params[key][2])]) for key in list(params.keys())}

        for search in pipeline:
            if search == 'random':
                best_params, score = self.random_search(params = params, group_size = 5, iterations = 50)
            elif search == 'grid':
                best_params, score = self.random_search(params = params)


            for key in best_params.keys():
                key_type = type(params[key][2])
                params_length = possible_params_lengths[key]
                new_min = key_type(best_params[key] - key_type(narrow_to * params_length) * params[key][2])
                new_max = key_type(best_params[key] + key_type(narrow_to * params_length) * params[key][2])
                if new_min > params[key][0]:
                    params[key][0] = new_min
                if new_max < params[key][1]:
                    params[key][1] = new_max
            print('new search ranges for parameters: {}'.format(params))

            print('performed {} serach with max score of {} and best parameters {}'.format(search, score, best_params))

        return best_params, score


    

In [18]:
real_data_df.columns

Index(['sensor_light', 'sensor_temperature', 'sensor_desktop', 'device_blinds',
       'device_lamp'],
      dtype='object')

In [19]:
XGB_PARAMS = {'n_estimators ': [20, 300, 20], 
                'learning_rate': [0.01, 0.1, 0.01], 
                'max_depth': [3, 300, 30], 
                'subsample': [0.8, 1, 0.05], 
                'colsample_bytree': [0.3, 0.8, 0.05],
                'gamma': [0, 5, 1],
                'verbosity': [0, 0, 1]}

X = deepcopy(real_data_df.drop(columns = ['device_blinds']))
y = deepcopy(real_data_df['device_blinds'])


In [20]:
# params = {'n_estimators ': [1, 50, 1], 
#                 'learning_rate': [5, 15, 5], 
#                 'max_depth': [0.01, 0.1, 0.01]}
# params_unpacked = {key: list(np.arange(params[key][0], params[key][1] + params[key][2], params[key][2])) for key in params.keys()}
# params_unpacked


In [21]:
# automl = AutoTuningHyperparameters(XGBClassifier, X, y, XGB_PARAMS, f1_score)

In [22]:
# automl pipeline

In [23]:
# best_params, score = automl.auto_tune_pipeline()


In [24]:
# best_params


In [25]:
# Next thing that is needed for this project is data preprocessing module. During the analysis I had to analyse data only from one  device. Unfortunately, this is not the case in real life iot system. We can have lots of devices, sending data in not parallel time (ex. varying in one second). Preprocessing module should be able to properly create array of data, with properly standarized features, and joined tables from dfferent devices. Also, as the data is in form of time series, it should be properly batched and padded.

In [26]:
class PreprocessData(object):

    @staticmethod
    def standarize(X, standarization_rule = 'sensor'):
        data = deepcopy(X.replace(['nan'], 0))
        for column_name in data.columns:
            if standarization_rule in column_name and data[column_name].std() != 0:
                data[column_name] = (data[column_name] - data[column_name].mean())/data[column_name].std()
        return data

    def __init__(self, data, standarization_rule = 'sensor', tolerance=pd.Timedelta('5s'), nan_value = -1, numerical_date = True):
        data_dfs = [pd.DataFrame(data[key]) for key in list(data.keys())]
        for data_df_index in range(len(data_dfs)):
            data_dfs[data_df_index]['date'] = pd.to_datetime(data_dfs[data_df_index]['date'])
            data_dfs[data_df_index] = data_dfs[data_df_index].sort_values(by='date')

        for data_df_index in range(len(data_dfs[:-1])):
            data_dfs[data_df_index + 1] = pd.merge_asof(data_dfs[data_df_index], data_dfs[data_df_index + 1], on = "date",                              tolerance=tolerance, direction='backward', suffixes = ['_' + key for key in list                                                       (data.keys())[data_df_index:data_df_index+2]]).fillna(nan_value)

        self.data_df = data_dfs[-1]
        if numerical_date == True:
            self.data_df['month']  = self.data_df['date'].dt.month
            self.data_df['day']  = self.data_df['date'].dt.day
            self.data_df['hour']  = self.data_df['date'].dt.hour
            self.data_df['minute']  = self.data_df['date'].dt.minute
            self.data_df['second']  = self.data_df['date'].dt.second
        
        self.data_df = self.standarize(self.data_df, standarization_rule=standarization_rule)

    def time_series(self, time_series_size = 3, forecast = 3, y_rule = 'device'):
        data_dfs  = [deepcopy(self.data_df.iloc[i:-time_series_size + i].drop('date', axis = 1).reset_index(drop = True)) for i in reversed(range(time_series_size))]
        for df_index in range(len(data_dfs)):
            data_dfs[df_index].columns = [column + '_' + str(df_index) for column in data_dfs[df_index].columns]
        X = pd.concat(data_dfs, axis = 1).iloc[:-forecast]
        Y = self.data_df[[column for column in self.data_df.columns if y_rule in column]].iloc[time_series_size:-forecast]
        return X, Y


In [27]:
data_preprocessor = PreprocessData({key: data[key] for key in list(data.keys())[1:]})

In [28]:
X, Y = data_preprocessor.time_series()

In [29]:
X

sensor_light_room_Jan_synchronized_0  sensor_temperature_0  \
0                                 0.268934              0.041599   
1                                 0.268934              0.041599   
2                                 0.268934              0.041599   
3                                 0.319296              0.041599   
4                                 0.268934              0.041599   
...                                    ...                   ...   
9989                              0.319296             -0.459891   
9990                              0.319296             -0.459891   
9991                              0.319296             -0.585263   
9992                              0.319296             -0.459891   
9993                              0.319296             -0.459891   

      sensor_desktop_0  device_blinds_0  device_lamp_0  \
0             0.717385                0              1   
1             0.717385                0              1   
2             0.717385                0              1   
3             0.717385                0              1   
4             0.717385                0              1   
...                ...              ...            ...   
9989          0.717385                0              1   
9990          0.717385                0              1   
9991          0.717385                0              1   
9992          0.717385                0              1   
9993          0.717385                0              1   

      sensor_light_external_sensors_0  month_0  day_0  hour_0  minute_0  ...  \
0                           -0.326229       10     13       0         0  ...   
1                           -0.326229       10     13       0         1  ...   
2                           -0.326229       10     13       0         1  ...   
3                           -0.326229       10     13       0         1  ...   
4                           -0.326229       10     13       0         2  ...   
...                               ...      ...    ...     ...       ...  ...   
9989                        -0.326229       10     15      23        57  ...   
9990                        -0.326229       10     15      23        57  ...   
9991                        -0.326229       10     15      23        57  ...   
9992                        -0.326229       10     15      23        58  ...   
9993                        -0.326229       10     15      23        58  ...   

      sensor_temperature_2  sensor_desktop_2  device_blinds_2  device_lamp_2  \
0                 0.041599          0.717385                0              1   
1                 0.041599          0.717385                0              1   
2                 0.041599          0.717385                0              1   
3                 0.041599          0.717385                0              1   
4                 0.041599          0.717385                0              1   
...                    ...               ...              ...            ...   
9989             -0.585263          0.717385                0              1   
9990             -0.585263          0.717385                0              1   
9991             -0.459891          0.717385                0              1   
9992             -0.459891          0.717385                0              1   
9993             -0.585263          0.717385                0              1   

      sensor_light_external_sensors_2  month_2  day_2  hour_2  minute_2  \
0                           -0.326229       10     13       0         0   
1                           -0.326229       10     13       0         0   
2                           -0.326229       10     13       0         0   
3                           -0.326229       10     13       0         1   
4                           -0.326229       10     13       0         1   
...                               ...      ...    ...     ...       ...   
9989                        -0.326229       1

In [30]:
Y

device_blinds  device_lamp
3                 0            1
4                 0            1
5                 0            1
6                 0            1
7                 0            1
...             ...          ...
9992              0            1
9993              0            1
9994              0            1
9995              0            1
9996              0            1

[9994 rows x 2 columns]

In [31]:
# automl = AutoTuningHyperparameters(XGBClassifier, X, Y['device_blinds'], XGB_PARAMS, f1_score)
# automl.auto_tune_pipeline()

In [32]:
# Code above was made into small library. Example usage: 

In [33]:
import AutoML
automl = AutoML.AutoTuningHyperparameters(XGBClassifier, {key: data[key] for key in list(data.keys())[1:]}, XGB_PARAMS, f1_score)
automl.auto_tune_pipeline()

new search ranges for parameters: {'n_estimators ': [80, 160, 20], 'learning_rate': [0.011999999999999997, 0.048, 0.01], 'max_depth': [3, 63, 30], 'subsample': [0.9100000000000001, 0.9900000000000002, 0.05], 'colsample_bytree': [0.4999999999999999, 0.6999999999999998, 0.05], 'gamma': [0, 2, 1], 'verbosity': [0, 0, 1]}
performed random serach with max score of 0.9989687177724303 and best parameters {'n_estimators ': 120, 'learning_rate': 0.03, 'max_depth': 3, 'subsample': 0.9500000000000002, 'colsample_bytree': 0.5999999999999999, 'gamma': 1, 'verbosity': 0}
value 1.01 for Parameter subsample exceed bound [0,1]
subsample: Row subsample ratio of training instance.
value 1.01 for Parameter subsample exceed bound [0,1]
subsample: Row subsample ratio of training instance.
value 1.01 for Parameter subsample exceed bound [0,1]
subsample: Row subsample ratio of training instance.
value 1.01 for Parameter subsample exceed bound [0,1]
subsample: Row subsample ratio of training instance.
value 1.

({'n_estimators ': 100,
  'learning_rate': 0.022,
  'max_depth': 63,
  'subsample': 0.9100000000000001,
  'colsample_bytree': 0.5499999999999999,
  'gamma': 2,
  'verbosity': 0},
 0.9989687177724303)

In [34]:
automl.data_preprocessor.standarization_matrix

date  sensor_light_room_Jan_synchronized  sensor_temperature  \
std    1.0                            0.198562            0.797624   
mean   0.0                            0.186600           21.566820   

      sensor_desktop  device_blinds  device_lamp  \
std         0.473665            1.0          1.0   
mean        0.660200            0.0          0.0   

      sensor_light_external_sensors  month  day  hour  minute  second  
std                        0.411943    1.0  1.0   1.0     1.0     1.0  
mean                       0.134388    0.0  0.0   0.0     0.0     0.0