In [1]:
import requests
import pandas as pd 
import numpy as np
from copy import deepcopy

In [2]:
data = requests.get('https://b718b51c1217.ngrok.io/data/6ytwk4ivTB7QkmlL0QPA1HNQ7NCOAb6Y').json()
data.keys()

dict_keys([&#39;room_Jan&#39;])

In [3]:
real_data_df = pd.DataFrame(data['room_Jan'])

In [4]:
# During the analysis I didn't know which column represents sensors, and which represents devices. 
# That is why I have performed some data analysis to determine it. Also all sensors values have been 
# standarized, so that machine learning algorithms can converge easly to global minimum of 
# cost function. 

In [5]:
columns = deepcopy(real_data_df.columns)

In [6]:
print(real_data_df[columns[0]].describe())
real_data_df[columns[0]].unique()
# strings representing date, primary key of each table in the smarthouse project database

count                        36550
unique                       36550
top       Fri Oct  2 23:01:20 2020
freq                             1
Name: date, dtype: object


array([&#39;Sun Sep 27 23:24:05 2020&#39;, &#39;Sun Sep 27 23:24:35 2020&#39;,
       &#39;Sun Sep 27 23:24:55 2020&#39;, ..., &#39;Tue Oct  6 15:46:37 2020&#39;,
       &#39;Tue Oct  6 15:46:58 2020&#39;, &#39;Tue Oct  6 15:47:18 2020&#39;],
      dtype=object)

In [7]:
print(real_data_df[columns[1]].describe())
real_data_df[columns[1]].unique()
# values between 0.0 and 0.65, it is probably light sensor

count    36550.000000
mean         0.204637
std          0.223791
min          0.000000
25%          0.000000
50%          0.140000
75%          0.430000
max          0.800000
Name: sensor_light, dtype: float64


array([0.49, 0.23, 0.24, 0.52, 0.51, 0.48, 0.5 , 0.46, 0.45, 0.43, 0.4 ,
       0.  , 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33, 0.34,
       0.35, 0.36, 0.37, 0.38, 0.39, 0.41, 0.42, 0.44, 0.47, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.22, 0.21, 0.2 , 0.19, 0.18, 0.17, 0.16, 0.15, 0.14, 0.13, 0.12,
       0.11, 0.1 , 0.09, 0.08, 0.07, 0.06, 0.05, 0.04, 0.03, 0.02, 0.01,
       0.66, 0.67, 0.68, 0.75, 0.7 , 0.77, 0.8 , 0.79, 0.71, 0.69])

In [8]:
print(real_data_df[columns[2]].describe())
real_data_df[columns[2]].unique()
# real values between 0 and 22.1, also some 'nan' included, probably it is temperature sensor

count     36550.0
unique       67.0
top          21.7
freq       3112.0
Name: sensor_temperature, dtype: float64


array([21, 20.9, 21.1, 21.2, 21.3, 21.4, 21.5, 21.6, 21.7, &#39;nan&#39;, 20.8,
       20.5, 20.2, 19.8, 19.6, 19.2, 19, 18.7, 18.5, 18.3, 18.1, 18, 17.8,
       17.7, 17.6, 17.5, 17.4, 17.3, 17.2, 17.1, 17, 16.9, 16.8, 16.7,
       16.6, 16.5, 16.4, 16.3, 16.2, 16.1, 17.9, 18.2, 18.4, 18.6, 18.8,
       18.9, 19.1, 19.3, 19.4, 19.5, 19.7, 19.9, 20, 20.1, 20.3, 20.4,
       20.6, 20.7, 21.8, 21.9, 22, 22.1, 22.2, 22.3, 22.4, 22.5, 22.6],
      dtype=object)

In [9]:
print(real_data_df[columns[3]].describe())
real_data_df[columns[3]].unique()
# only zeros and ones, it is controllable divice

count    36550.000000
mean         0.307360
std          0.461406
min          0.000000
25%          0.000000
50%          0.000000
75%          1.000000
max          1.000000
Name: sensor_desktop, dtype: float64


array([0, 1], dtype=int64)

In [10]:
print(real_data_df[columns[4]].describe())
real_data_df[columns[4]].unique()
# only zeros and ones, it is controllable divice

count    36550.000000
mean         0.515486
std          0.499767
min          0.000000
25%          0.000000
50%          1.000000
75%          1.000000
max          1.000000
Name: device_blinds, dtype: float64


array([0, 1], dtype=int64)

In [11]:
print(real_data_df[columns[5]].describe())
real_data_df[columns[5]].unique()
# only zeros and ones, it is controllable divice

count    36550.000000
mean         0.113735
std          0.317493
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: device_lamp, dtype: float64


array([1, 0], dtype=int64)

In [12]:
#real_data_df.columns = ['date', 'sensor_1', 'sensor_2', 'device_1', 'device_2', 'device_3']
real_data_df.index = real_data_df['date']
real_data_df = real_data_df.drop(columns = ['date'])

In [13]:
real_data_df

sensor_light sensor_temperature  sensor_desktop  \
date                                                                        
Sun Sep 27 23:24:05 2020          0.49                 21               0   
Sun Sep 27 23:24:35 2020          0.23                 21               0   
Sun Sep 27 23:24:55 2020          0.23                 21               0   
Sun Sep 27 23:25:15 2020          0.24                 21               0   
Sun Sep 27 23:25:35 2020          0.23                 21               0   
...                                ...                ...             ...   
Tue Oct  6 15:45:57 2020          0.42               22.4               1   
Tue Oct  6 15:46:17 2020          0.42               22.4               1   
Tue Oct  6 15:46:37 2020          0.42               22.4               1   
Tue Oct  6 15:46:58 2020          0.42               22.4               1   
Tue Oct  6 15:47:18 2020          0.42               22.3               1   

                          device_blinds  device_lamp  
date                                                  
Sun Sep 27 23:24:05 2020              0            1  
Sun Sep 27 23:24:35 2020              0            1  
Sun Sep 27 23:24:55 2020              0            1  
Sun Sep 27 23:25:15 2020              0            1  
Sun Sep 27 23:25:35 2020              0            1  
...                                 ...          ...  
Tue Oct  6 15:45:57 2020              1            1  
Tue Oct  6 15:46:17 2020              1            1  
Tue Oct  6 15:46:37 2020              1            1  
Tue Oct  6 15:46:58 2020              1            1  
Tue Oct  6 15:47:18 2020              1            1  

[36550 rows x 5 columns]

In [14]:
# Next step is to determine best rule indiction algorithm. Our goal is to find a rule 
# of behaviours between devices and sensors, so that our algorithm can predict properly when it should
# activate each device. 2 algorithms I am going to compare are Decision Trees, Random Forest and Extreeme Gradient Boosted Trees.

In [15]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn import metrics

from copy import deepcopy
import itertools

In [16]:
from sklearn.metrics import fbeta_score

def f1_score(y_true, y_pred, threshold = 0.5):
    y_pred_class = y_pred >= threshold
    y_true = y_true == 1
    return fbeta_score(y_true, y_pred_class, beta = 1)

In [17]:
class AutoTuningHyperparameters(object):
    @staticmethod
    def standarize(X, standarization_rule = None):
        data = deepcopy(X.replace(['nan'], 0))
        for column_name in data.columns:
            if 'sensor' in column_name:
                data[column_name] = (data[column_name] - data[column_name].mean())/data[column_name].std()
        return data

    @staticmethod
    def generate_all_possible_params(params):
        params_unpacked = {key: list(np.arange(params[key][0], params[key][1] + params[key][2], params[key][2])) for key in                     params.keys()}
        keys, values = zip(*params_unpacked.items())
        possible_params = [dict(zip(keys, v)) for v in itertools.product(*values)]
        return possible_params

    def __init__(self, model, X, y, params, cost):
        self.model = model 
        X = self.standarize(X) 
        self.X_train = X[:int(0.7*len(X))]
        self.X_test = X[int(0.7*len(X)):]
        self.y_train = y[:int(0.7*len(y))]
        self.y_test = y[int(0.7*len(y)):]
        self.params = params
        self.cost = cost
        self.best_model = None
    
    def fit_model(self, params):
        model = self.model(**params)
        try:
            model.fit(self.X_train, self.y_train)
            predictions = model.predict(self.X_test)
            return model, self.cost(self.y_test, predictions)
        except:
            return None, 0
    
    def grid_search(self, params = None, verbose = 1):
        if params:
            params = self.generate_all_possible_params(params)
        else:
            params = self.generate_all_possible_params(self.params)
        models = []
        for index, parameters in enumerate(params):
            model, ratio = self.fit_model(parameters)
            models.append([parameters, ratio])

            if verbose >= 1:
                print('{:.4f}'.format((index+1)/len(params)), end = '\r')

        sorted_models = [[x[0], x[1]] for x in sorted(models, key = lambda x: x[1])]
        self.best_model = sorted_models[-1]
        return self.best_model[0], self.best_model[1]

    def random_search(self, verbose = 1, group_size = 5, iterations = 20, params = None):
        if params:
            params = self.generate_all_possible_params(params)
        else:
            params = self.generate_all_possible_params(self.params)

        models = []
        for iteration in range(iterations):
            random_group = np.random.choice(params, group_size)
            for random_params in random_group:
                model, ratio = self.fit_model(random_params)
                models.append([random_params, ratio])

            if verbose >= 1:
                print('{:.4f}'.format((iteration+1)/iterations), end = '\r')

        sorted_models = [[x[0], x[1]] for x in sorted(models, key = lambda x: x[1])]
        self.best_model = sorted_models[-1]
        return self.best_model[0], self.best_model[1]

    def genetic_search(self):
        pass 

    def auto_tune_pipeline(self, pipeline = ['random', 'grid'], narrow_to = 0.2, params = None):
        if params:
            params = params
        else:
            params = self.params
        
        possible_params_lengths = {key: len([param for param in np.arange(params[key][0], params[key][1], params[key][2])]) for key in list(params.keys())}

        for search in pipeline:
            if search == 'random':
                best_params, score = self.random_search(params = params, group_size = 5, iterations = 50)
            elif search == 'grid':
                best_params, score = self.random_search(params = params)


            for key in best_params.keys():
                key_type = type(params[key][2])
                params_length = possible_params_lengths[key]
                new_min = key_type(best_params[key] - key_type(narrow_to * params_length) * params[key][2])
                new_max = key_type(best_params[key] + key_type(narrow_to * params_length) * params[key][2])
                if new_min > params[key][0]:
                    params[key][0] = new_min
                if new_max < params[key][1]:
                    params[key][1] = new_max
            print('new search ranges for parameters: {}'.format(params))

            print('performed {} serach with max score of {} and best parameters {}'.format(search, score, best_params))

        return best_params, score


    

In [18]:
real_data_df.columns

Index([&#39;sensor_light&#39;, &#39;sensor_temperature&#39;, &#39;sensor_desktop&#39;, &#39;device_blinds&#39;,
       &#39;device_lamp&#39;],
      dtype=&#39;object&#39;)

In [19]:
XGB_PARAMS = {'n_estimators ': [20, 300, 20], 
                'learning_rate': [0.01, 0.1, 0.01], 
                'max_depth': [3, 300, 30], 
                'subsample': [0.8, 1, 0.05], 
                'colsample_bytree': [0.3, 0.8, 0.05],
                'gamma': [0, 5, 1],
                'verbosity': [0, 0, 1]}

X = deepcopy(real_data_df.drop(columns = ['device_blinds']))
y = deepcopy(real_data_df['device_blinds'])


In [20]:
# params = {'n_estimators ': [1, 50, 1], 
#                 'learning_rate': [5, 15, 5], 
#                 'max_depth': [0.01, 0.1, 0.01]}
# params_unpacked = {key: list(np.arange(params[key][0], params[key][1] + params[key][2], params[key][2])) for key in params.keys()}
# params_unpacked


In [21]:
automl = AutoTuningHyperparameters(XGBClassifier, X, y, XGB_PARAMS, f1_score)

In [22]:
# automl pipeline

In [23]:
best_params, score = automl.auto_tune_pipeline()


new search ranges for parameters: {&#39;n_estimators &#39;: [260, 300, 20], &#39;learning_rate&#39;: [0.022, 0.058, 0.01], &#39;max_depth&#39;: [153, 273, 30], &#39;subsample&#39;: [0.9600000000000002, 1, 0.05], &#39;colsample_bytree&#39;: [0.3999999999999999, 0.6, 0.05], &#39;gamma&#39;: [3, 5, 1], &#39;verbosity&#39;: [0, 0, 1]}
performed random serach with max score of 0.9059144676979072 and best parameters {&#39;n_estimators &#39;: 300, &#39;learning_rate&#39;: 0.04, &#39;max_depth&#39;: 213, &#39;subsample&#39;: 1.0000000000000002, &#39;colsample_bytree&#39;: 0.49999999999999994, &#39;gamma&#39;: 4, &#39;verbosity&#39;: 0}
new search ranges for parameters: {&#39;n_estimators &#39;: [260, 300, 20], &#39;learning_rate&#39;: [0.022, 0.05, 0.01], &#39;max_depth&#39;: [153, 213, 30], &#39;subsample&#39;: [0.9600000000000002, 1, 0.05], &#39;colsample_bytree&#39;: [0.3999999999999999, 0.5999999999999999, 0.05], &#39;gamma&#39;: [4, 5, 1], &#39;verbosity&#39;: [0, 0, 1]}
performed grid se

In [24]:
best_params


{&#39;n_estimators &#39;: 300,
 &#39;learning_rate&#39;: 0.032,
 &#39;max_depth&#39;: 153,
 &#39;subsample&#39;: 0.9600000000000002,
 &#39;colsample_bytree&#39;: 0.4999999999999999,
 &#39;gamma&#39;: 5,
 &#39;verbosity&#39;: 0}

In [25]:
# Next thing that is needed for this project is data preprocessing module. During the analysis I had to analyse data only from one device. 
# Unfortunately, this is not the case in real life iot system. We can have lots of devices, sending data in not parallel time (ex. varying in one second). 
# Preprocessing module should be able to properly create array of data, with properly standarized features, and joined tables from dfferent devices. 
# Also, as the data is in form of time series, it should be properly batched and padded.